from . import (
    person,
    patient,
    doctor,
    doctor_schedule,
    visit,
    personal_doctor_history,
    emergency_contact,
    diagnosis,
    disease_type,
    disease,
    medical_test_type,
    medical_test,
    sample_type,
)
